### ISSUE TITLE
Migration to material-ui v1

### ISSUE THREAD

**Issue by ythecombinator** [networknt/react-schema-form#100]
Hey, I've made a quick search across the docs and the issues here and I haven't found anything related to porting this to use `material-ui v1.x` and I'd like to know if you guys have any plans on this.

It turns out that your project is the best alternative I could find for using `react-jsonschema-form` on my current stack–which is based on `@material-ui/core v1.2.1`–but it seems to me that it heavily relies on `material-ui v0.x`. 

In case you guys don't have any plans on this, are there any practices that you recommend? I mean... Things to avoid using the workarounds required to keep two different versions of `material-ui` (e.g. having two `MuiThemeProvider`s).

Thanks 😄

**Comment by thefringeninja** [comment]
In the meantime one thing you can do is shim it.

**Comment by stevehu** [comment]
@ythecombinator There is a new branch react16 which has been upgraded to React 16 and material-ui 1.x. It is still working in progress.

**Comment by ythecombinator** [comment]
Thanks for your suggestion, @thefringeninja. And thanks for the feedback, @stevehu. 

Please allow me to ask; how's the progress on that branch? Is there any roadmap/something similar or any estimations? Thank you very much.

**Comment by stevehu** [comment]
Progress is very slow as I have too many other projects that need my attention. It is open for contributions and we can work together.

**Comment by dogada** [comment]
I started to work on finishing migration to React 16 and Material UI 1.0. You can track progress at https://github.com/dogada/react-schema-form/tree/mui10

**Comment by stevehu** [comment]
@dogada Cool!!! That is a lot of work in the last couple of days. Thanks.

**Comment by dogada** [comment]
@stevehu what do you mind about modernizing whole codebase as well, i.e. switch indentation to 2 space (at the moment 4 is used) and remove semicolons? In fact switch to use https://standardjs.com/?

**Comment by stevehu** [comment]
@dogada That is a great idea. It will make maintenance work much easier. Thanks.

**Comment by americos** [comment]
@dogada I looked at your branch and seems like you have being doing great progress 👍 Would you mind sharing what's your roadmap plan?

**Comment by stevehu** [comment]
@dogada @americos I have merged the big PR from @SadMonster into react16 branch. I am testing it now and it looks like very stable. Will merge back to develop branch soon. Thanks.

**Comment by dogada** [comment]
Some of the changes from above-mentioned merged PR duplicate my earlier changes. I plan to review them in detail and merge latest upstream changes next days. I expect to send PR this week

**Comment by stevehu** [comment]
@dogada This is so cool. I am planning to focus on the light-portal the next several weeks and react-schema-form will be an important part of the UI. Hope we can stabilize it soon and have a release soon. Thanks.

**Comment by dogada** [comment]
@stevehu I repared the pull request. Please review #111

**Comment by stevehu** [comment]
With a lot of help from the community, we can say we have upgraded to the latest material-ui successfully. Thanks a lot for your help.
