### ISSUE TITLE
Model not updating

### ISSUE THREAD

**Issue by ivanthemeh** [networknt/react-schema-form#101]
No matter what I do I cannot get the model to update when changing data... I am clicking on events to change the state in a calendar and I have tried using props and state and it will not update..Please and thanks for any help.

**Comment by ivanthemeh** [comment]
Im sorry I was reading a few other issues and it looks like I was trying to use the model to update the form fields values and thats not how this package works..I guess.

**Comment by stevehu** [comment]
The model will only be initialized during the startup to set the default values. After that, you update the form and the model will be updated accordingly.
