### ISSUE TITLE
How can turn all invalid fields red on submit 

### ISSUE THREAD

**Issue by simon998yang** [networknt/react-schema-form#106]
Field will turn red and show validation messages only when editing it. How can mark all invalid fields red and show validation messages with them when submitting the form?

**Comment by stevehu** [comment]
Is this the current behavior? We have a bug right now that need to be fixed as the form will be validated right after the initialization. During the editing, the validation is done automatically so the invalid fields are always showing up until you fill in all valid values. Can you elaborate a little bit more details? Thanks.

**Comment by stevehu** [comment]
We have released several versions recently and the library has been tested with several applications. I think this issue is fixed already.
