### ISSUE TITLE
Material UI Typography will be depreciated 

### ISSUE THREAD

**Issue by T3-JacksonBush** [networknt/react-schema-form#130]
<img width="732" alt="warning" src="https://user-images.githubusercontent.com/44375177/47306440-7c5fe600-d5fa-11e8-9363-c8e424c7db27.png">

Following that [link](https://material-ui.com/style/typography/#migration-to-typography-v2), an immediate switch to typography v2 can be made if you can simply pass useNextVariants: true when calling createMuiTheme:

~~~~
const theme = createMuiTheme({
  typography: {
    useNextVariants: true,
  },
});
~~~~

Can this be done?

**Comment by stevehu** [comment]
@T3-JacksonBush Thanks a lot for your help. It works like a magic.
