### ISSUE TITLE
Backend validation example

### ISSUE THREAD

**Issue by ponahoum** [networknt/react-schema-form#131]
Hi,

I easily managed to use to front validation of forms with the "pattern" attribute, when I use it, it throws a "red" error underneath the field, which works great as intended :). However, I can't find an example of backend validation, here's my situation :

-> On form submit, I call a fetch and gather the data from my API (Symfony API)
-> If the form is **not validated in the back end,** an **errors** field is populated in the json response.

How can I handle this error  to get a **"red" validation error message underneath the concerned field**  ? Is that a feature of your project ?

Thank you very much for your awesome project :)

**Comment by stevehu** [comment]
@ponahoum Thanks a lot for your encouraging words. We are using the form as front end and using our own frameworks, light-rest-4j, light-graphql-4j and light-hybrid-4j as backend. These frameworks are leveraging the [json-schema-validator](https://github.com/networknt/json-schema-validator) for backend validation with the same schema used in the front end.

**Comment by ponahoum** [comment]
Thank you for your answer @stevehu. Do you have a link to a simple example of the right Json to return to have backend validation errors to be displayed in front directly under the concerned unvalidated field ? A bit like what is explained here on the [Json Schema Form Doc](https://github.com/json-schema-form/json-schema-form/wiki/Documentation#inject-errors-into-form-aka-backend-validation)

I could inject a _validationMessage_ in one of the properties of my Schema, but would it be the right way to do ? (considering the fact that we can only put one validationMessage, and that I have really no idea how to manually trigger the validationMessage without the pattern attribute)

**Comment by ponahoum** [comment]
Thank you for your answer @stevehu. You perfectly answered to my question; as you said, it makes sense to create a separate section in the ui for additional backend validation rules (ex : check the unicity of a username during a register process) and I'll do that :) Have a nice end of week
