### ISSUE TITLE
Validation behaviour on load

### ISSUE THREAD

**Issue by swetapatnaik** [networknt/react-schema-form#136]
How can I disable the validation on load. Currently when the form loads the validation immediately fires up and shows the field errors. However I want the validation to fire up when the field is focused and then blurred without entering any data. How can I achieve this. Thanks in advance.

**Comment by stevehu** [comment]
@swetapatnaik Yes. I realize this issue during my test with the example. It was introduced recently and I will mark it as a bug to get it fixed. Thanks for bringing it up.

**Comment by swetapatnaik** [comment]
Thanks Steve

**Comment by naeemba** [comment]
What is the best behavior for this issue?
In our project we disabled the validation at start, when user clicks on submit button, validation will be enabled, after that it will work as user types. Is it the correct behavior that you want too?

**Comment by stevehu** [comment]
@naeemba That would be the right behavior. Currently, if you just load the form normally, it validates the form immediately and shows all the invalid fields in red. How do you disable the validation at startup? Thanks.

**Comment by naeemba** [comment]
Actually as we made some minor changes to our version of this project, I am not sure where to start on this, but I'll work on this issue and will create a PR for that.
Thanks

**Comment by stevehu** [comment]
@naeemba Thanks a lot for your PR. I tested with the example and it works perfectly.
