### ISSUE TITLE
Incorrect errors for not required null fields

### ISSUE THREAD

**Issue by naeemba** [networknt/react-schema-form#160]
Currently, if you try to validate an object with some null values for properties of that object (These properties are not required), it will return some validation errors, which is incorrect.

**Comment by stevehu** [comment]
@naeemba I have published 0.6.12 for the fix. Thanks a lot for your help. 

https://github.com/networknt/react-schema-form/releases/tag/0.6.12

**Comment by naeemba** [comment]
Thank you so much, I really hope I find some time to improve the documentation and also upgrade the dependencies.

**Comment by stevehu** [comment]
I am currently using it for light-portal development. I will see if I can start the documentation as part of the light-platform and link from this project.
