### ISSUE TITLE
Array of string enum items produces no form control

### ISSUE THREAD

**Issue by fauxsoup** [networknt/react-schema-form#162]
I get an empty div when using the following schema:

```json
{
    "type": "array",
    "items": {
        "type": "string",
        "enum": ["a","b","c"]
    }
}
```

I expect to receive an array control allowing me to add/remove items, with a selection menu or radio buttons to select strings.

I am using React 16.7.0. There is no error output in the console.

Please let me know if I can provide any other information.

**Comment by stevehu** [comment]
@fauxsoup I think this example is the same as yours. The accessLevel is an array of enum in the example. 

https://github.com/networknt/react-schema-form/blob/master/example/data/arrayselect.json

**Comment by fauxsoup** [comment]
Thank you; I was able to get it working by explicitly specifying the multiselect component. When reviewing everything, it looks like by default it attempts to use the checkboxes control, which does not work with this schema.

I will close this issue since I'm able to work around.

**Comment by stevehu** [comment]
you can specify checkboxes vs multi-select in the form section.
