### ISSUE TITLE
Array type renders property name on each iteration

### ISSUE THREAD

**Issue by agrishun** [networknt/react-schema-form#17]
If I use array type, it adds for each item `<label>property.name</label>` and wrap it with `<ol>`.
I think `{array}` should consists of only `<li>` elements.
On the screenshot below you can see the difference. left side - before my changes, and the right side - after.
![im](https://cloud.githubusercontent.com/assets/3495582/14440637/19a8baf6-0031-11e6-9f35-c236691a17c8.jpg)

**Comment by stevehu** [comment]
A new version 0.2.8 is published. Thanks for your help.
