### ISSUE TITLE
Schema ace editor not rendering and no form being generated in example.

### ISSUE THREAD

**Issue by NicholasAzar** [networknt/react-schema-form#19]
Hello,

Using the latest code for the example in master, the form is not being generated and the schema json ace editor is not being rendered.

From console, I see the following error on load:
Uncaught Error: misspelled option "enableBasicAutocompletion"

And after selecting an example:
Uncaught TypeError: Cannot read property 'getValue' of undefined

Using chrome 49.0.2623.87 (64-bit) on ubuntu 15.10 with node v5.9.0.

Screenshot below, please let me know if I'm doing something wrong with this. I also disabled all browser extensions/plugins just in case. Installed with npm install, started with npm start.

![screenshot from 2016-04-16 14-57-50](https://cloud.githubusercontent.com/assets/10523372/14583069/b3c7a712-03e4-11e6-9856-738631d1b564.png)

Thank you,

**Comment by stevehu** [comment]
@NicholasAzar Have you done a fresh npm install? If yes, then it must be some of the dependencies upgraded and broken. I will tried it tonight for a fresh install.

**Comment by stevehu** [comment]
React-ace is the culprit. I have locked it down to 3.1.0. Both 3.2.0 and 3.3.0 have bugs and behave differently. Please checkout the latest and run fresh npm install.

**Comment by NicholasAzar** [comment]
Verified, all good. Thank you Steve!
