### ISSUE TITLE
Is it possible to use definitions?

### ISSUE THREAD

**Issue by chinshr** [networknt/react-schema-form#20]
These could be referenced from within a schema, like the following example:

```javascript
{
  "$schema": "http://json-schema.org/draft-04/schema#",

  "definitions": {
    "notes": {
      "type": "object",
      "properties": {
        "classification": {
          "type": "string",
          "enum": [
            "Lite",
            "Premium",
            "Plus",
          ]
        }
      }
    }
  },

  "title": "Customer Creative Brief",
  "type": "object",
  "properties": {
    "notes": { "$ref": "#/definitions/notes" }
  }
}
```

**Comment by stevehu** [comment]
ref is not supported at the moment; however, a group of people are working on it to produce a common core shared between angular-schema-form, react-schema-form etc. Stay tuned.

https://github.com/json-schema-form/json-schema-form-core

**Comment by chinshr** [comment]
I duplicated [this](https://github.com/json-schema-form/json-schema-form-core/issues/1) issue over on the [core](https://github.com/json-schema-form/json-schema-form-core) team. Thanks for the link!
