### ISSUE TITLE
Select component drops value after changing from dropdown

### ISSUE THREAD

**Issue by stevehu** [networknt/react-schema-form#3]
I don't know if this was introduced by splitting bootstrap and material-ui. The material-ui version of select is not working now. The default value display is OK but once the value is changed, it becomes empty.

**Comment by NicholasAzar** [comment]
Will debug this asap, thank you for letting me know!

**Comment by NicholasAzar** [comment]
I might be misunderstanding the problem... if we take the "Simple" form for example, by default it's set to LOCAL, if you change it to SIT1 then try to select a different value, there are no other options? I can't seem to reproduce this on firefox or chrome.

Please advise

**Comment by stevehu** [comment]
Hi Nick,

Here is the screenshot. You can see I have selected option b from the
dropdown but It is still empty on the form. The default value "a" displayed
OK though.

BTW, I have rebuilt the intidb.json in the develop branch with all the
latest code and data. You can try the e-commerce from efg folder.

npm install
npm start

example:8001/webpack-dev-server/

make  sure you have example in /etc/hosts pointing to 127.0.0.1

Merry Christmas!!!

Steve
[image: Inline image 1]

**Comment by stevehu** [comment]
It looks like a temp release of material-ui is the culprit. With the latest release, everything works. Thanks @NicholasAzar
