### ISSUE TITLE
Don't Call PropTypes Warning

### ISSUE THREAD

**Issue by ikostic** [networknt/react-schema-form#33]
I get following error on page where form is used:

> warning.js:44 Warning: You are manually calling a React.PropTypes validation function for the `onEnterKeyDown` prop on `TextField`. This is deprecated and will not work in the next major version. You may be seeing this warning due to a third-party PropTypes library. See https://fb.me/react-warning-dont-call-proptypes for details.warning @ warning.js:44checkType @ ReactPropTypes.js:120validate @ flexboxIE.js:20checkReactTypeSpec @ checkReactTypeSpec.js:58validatePropTypes @ ReactElementValidator.js:153createElement @ ReactElementValidator.js:187render @ Text.js:48_renderValidatedComponentWithoutOwnerOrContext @ ReactCompositeComponent.js:832_renderValidatedComponent @ ReactCompositeComponent.js:859performInitialMount @ ReactCompositeComponent.js:383mountComponent @ ReactCompositeComponent.js:262mountComponent @ ReactReconciler.js:47performInitialMount @ ReactCompositeComponent.js:397mountComponent @ ReactCompositeComponent.js:262mountComponent @ ReactReconciler.js:47updateChildren @ ReactChildReconciler.js:119_reconcilerUpdateChildren @ ReactMultiChild.js:213_updateChildren @ ReactMultiChild.js:316updateChildren @ ReactMultiChild.js:303_updateDOMChildren @ ReactDOMComponent.js:960updateComponent @ ReactDOMComponent.js:780receiveComponent @ ReactDOMComponent.js:734receiveComponent @ ReactReconciler.js:129_updateRenderedComponent @ ReactCompositeComponent.js:784_performComponentUpdate @ ReactCompositeComponent.js:753updateComponent @ ReactCompositeComponent.js:670receiveComponent @ ReactCompositeComponent.js:564receiveComponent @ ReactReconciler.js:129updateChildren @ ReactChildReconciler.js:107_reconcilerUpdateChildren @ ReactMultiChild.js:213_updateChildren @ ReactMultiChild.js:316updateChildren @ ReactMultiChild.js:303_updateDOMChildren @ ReactDOMComponent.js:960updateComponent @ ReactDOMComponent.js:780receiveComponent @ ReactDOMComponent.js:734receiveComponent @ ReactReconciler.js:129updateChildren @ ReactChildReconciler.js:107_reconcilerUpdateChildren @ ReactMultiChild.js:213_updateChildren @ ReactMultiChild.js:316updateChildren @ ReactMultiChild.js:303_updateDOMChildren @ ReactDOMComponent.js:960updateComponent @ ReactDOMComponent.js:780receiveComponent @ ReactDOMComponent.js:734receiveComponent @ ReactReconciler.js:129updateChildren @ ReactChildReconciler.js:107_reconcilerUpdateChildren @ ReactMultiChild.js:213_updateChildren @ ReactMultiChild.js:316updateChildren @ ReactMultiChild.js:303_updateDOMChildren @ ReactDOMComponent.js:960updateComponent @ ReactDOMComponent.js:780receiveComponent @ ReactDOMComponent.js:734receiveComponent @ ReactReconciler.js:129_updateRenderedComponent @ ReactCompositeComponent.js:784_performComponentUpdate @ ReactCompositeComponent.js:753updateComponent @ ReactCompositeComponent.js:670performUpdateIfNecessary @ ReactCompositeComponent.js:578performUpdateIfNecessary @ ReactReconciler.js:163runBatchedUpdates @ ReactUpdates.js:151perform @ Transaction.js:138perform @ Transaction.js:138perform @ ReactUpdates.js:90flushBatchedUpdates @ ReactUpdates.js:173closeAll @ Transaction.js:204perform @ Transaction.js:151batchedUpdates @ ReactDefaultBatchingStrategy.js:63enqueueUpdate @ ReactUpdates.js:201enqueueUpdate @ ReactUpdateQueue.js:25enqueueSetState @ ReactUpdateQueue.js:210ReactComponent.setState @ ReactComponent.js:64(anonymous function) @ item.js:49

When I follow link for warning description:

> In a future major release of React, the code that implements PropType validation functions will be stripped in production. Once this happens, any code that calls these functions manually (that isn't stripped in production) will throw an error.
> 
> If you don't fix the warning, this code will crash in production with React 16.

Can we expect new release which will address this issue?

Regards

**Comment by stevehu** [comment]
@ikostic Thanks for pointing it out. I am working on it to upgrade the dependencies. Stay tuned.

**Comment by stevehu** [comment]
Upgrade to the latest react and the issue should be resolved. Thanks @devel-pa.
