### ISSUE TITLE
TextField value does not clear when changing Form type

### ISSUE THREAD

**Issue by diverslicense** [networknt/react-schema-form#34]
In the demo, 
1. In "Simple" form, enter value in Email field > value in Model
2. Change to "Address" form > value from step 1 populates Last Name field
3. Change back to "Simple form" > email value still populated in form but value not in Model

![schemaformgif](https://cloud.githubusercontent.com/assets/5516289/18286547/251ac4ea-7428-11e6-9593-acac6d1b616a.gif)

Shouldn't the values clear when the user selects a different form? I am having trouble with this in my own app where the form is not re-rendering even though the state has changed.

**Comment by stevehu** [comment]
@diverslicense This should be addressed in release 0.2.10. Please let me know if you have questions.
