### ISSUE TITLE
Error with "enum" string inputs

### ISSUE THREAD

**Issue by aL3xa** [networknt/react-schema-form#42]
I'm having a problem with `enum` property in form input definition. Given this schema

```{js}
{
    type: 'object',
    properties: {
      email: {
        type: 'string',
        title: 'E-mail address',
      },
      timeFormat: {
        type: 'string',
        title: 'Time format',
        enum: ['12', '24'],
      },
    },
    required: ['email', 'timeFormat'],
  },
```
I get a following error:

```
TypeError: Cannot read property '[object Array]' of undefined
new Select
webpack:///./~/react-schema-form/lib/Select.js?:46:44
eval
webpack:///./~/react-proxy/modules/createClassProxy.js?:95:24
instantiate
webpack:///./~/react-proxy/modules/createClassProxy.js?:103:9
Select
webpack:///./~/react-proxy/modules/createClassProxy.js?
eval
webpack:///./~/react-dom/lib/ReactCompositeComponent.js?:295:18
measureLifeCyclePerf
webpack:///./~/react-dom/lib/ReactCompositeComponent.js?:75:12
ReactCompositeComponentWrapper._constructComponentWithoutOwner
webpack:///./~/react-dom/lib/ReactCompositeComponent.js?:294:16
ReactCompositeComponentWrapper._constructComponent
webpack:///./~/react-dom/lib/ReactCompositeComponent.js?:280:21
ReactCompositeComponentWrapper.mountComponent
webpack:///./~/react-dom/lib/ReactCompositeComponent.js?:188:21
Object.mountComponent
webpack:///./~/react-dom/lib/ReactReconciler.js?:46:35
```

Everything works fine if I omit `enum` field. Anyone had similar issue?

**Comment by stevehu** [comment]
I am using enum all the time and there is no issue. In this [demo](http://networknt.github.io/react-schema-form/), select Basic JSON Schema Type in the dropdown and you can see the example schema using enum. Please note that the demo site might using an older version, however, the examples are in the source code and you can use it to try your schema just adding an extra example. Let me know if it still not working for you. Thanks and happy coding.

**Comment by oceanic815recovery** [comment]
I am experiencing the exact same issue with the same exception. I am on version 0.3.8

**Comment by oceanic815recovery** [comment]
This is the exact commit which breaks it: https://github.com/networknt/react-schema-form/commit/2dcc1fd5fe6aac901635eaac0983f21f154c2b06

I locally reverted that commit in my copy of react-schema-form and now enums work properly
