### ISSUE TITLE
Move react to peer dependencies, react-dom to dev dependencies ?

### ISSUE THREAD

**Issue by stropitek** [networknt/react-schema-form#44]
react is now a direct dependency of the project. I think the best practice is to put in `peerDependencies`, to avoid having conflicting versions of react.

Also the libraries used in the examples should be in devDependencies (`react-dom`, `react-tap-event-plugin`) , they are not needed by a third party using the library.

**Comment by stevehu** [comment]
Thanks for pointing out these issues. I am focusing on the server side these days and there are a lot of things need to be updated. Will start to look into it once I can take a break from other projects. Meanwhile pull request is welcomed.

**Comment by stropitek** [comment]
I will do another PR because I forgot to add the dependencies that I moved to `peerDependencies` in `devDependencies` as well. The examples need those to function.

**Comment by stropitek** [comment]
I also think the add-on dev dependency (https://github.com/networknt/react-schema-form-rc-select) project needs to be cleaned up, because it has all the same dependencies. I will open a separate issue for that

**Comment by stropitek** [comment]
https://github.com/networknt/react-schema-form-rc-select/issues/3

**Comment by stevehu** [comment]
Cool. Rc-select should worked the same way. This remind me to release both togethor.

**Comment by stropitek** [comment]
Can you make a release of the package? I'm happy with the way dependencies work now. I think semver-minor.

**Comment by stevehu** [comment]
@stropitek Thanks a lot for your help. I just published a new release, please review and let me know if you have questions. 

https://github.com/networknt/react-schema-form/releases/tag/0.3.5
