### ISSUE TITLE
file image upload thumbnail support

### ISSUE THREAD

**Issue by cuongngosa** [networknt/react-schema-form#50]
Hi, do it support image thumbnail for file type at the moment ?

**Comment by stevehu** [comment]
We need to create a customized file input. I used to have one for angular schema form. I will mark this as feature and ask for help from the community.

**Comment by stevehu** [comment]
Quote from @cuongngosa "My case is whenever user select file to upload, instantly thumbnail image will be display at the right of Browse button"

**Comment by cuongngosa** [comment]
nvm, I figure out
Thanks stevehu

**Comment by stevehu** [comment]
@cuongngosa Could you please elaborate how to do that? Thanks.

**Comment by cuongngosa** [comment]
Actually, I use react-dropzone-component to do multiple upload with support lots of upload feature, then I just load image list to a drop down list for user to select and submit image name value on json formData @stevehu

**Comment by stevehu** [comment]
@cuongngosa Thanks for letting us know. Happy coding.
