### ISSUE TITLE
two field refer to same key, not updating each other

### ISSUE THREAD

**Issue by simon998yang** [networknt/react-schema-form#54]
If I put 2 fields which refer to same key. i.e they display correctly accordingly to init data. But if you update one field, the other one is not updated.

angular schema form can handle it out of box.

Any suggestion?

**Comment by stevehu** [comment]
The react-schema-form uses an early version of angular-schema-form lib as core. So internally, they should work the same way in term of parsing and validation; however, the way angular 1.x and react handle UI is different, especially how key is treated. I am guessing that you use the same key for two fields is to copy one field to another automatically. In that case, it is easy to do with flux based on event and it is how react handle this kind of binding. If your use case is different, please let us know and we can discuss how to work around it. Thanks.

**Comment by simon998yang** [comment]
Yes, the use case is to copy one field value to another automatically. The problem is if we use a centralized data store, every time we change a field value, and it will ultimately change the data pass down the form.  So the whole form will get re-rendered for each field change. We will run into performance issue not for a very big form.

**Comment by stevehu** [comment]
React rendering is a little different than Angular 1.x and the form won't be re-rendered if only one of the fields is changed. Give it a try and see if you have performance issue. I am using it intensively with influx and never experience any performance issue and it is very common in React SPA.
