### ISSUE TITLE
missing dependency

### ISSUE THREAD

**Issue by herzaso** [networknt/react-schema-form#67]
It seems that there is a missing dependency on `material-ui` in the `package.json` file

> ./node_modules/react-schema-form/lib/Number.js
> Module not found: Can't resolve 'material-ui/TextField' in 'C:\Development\client\node_modules\react-schema-form\lib'

**Comment by stevehu** [comment]
Material-ui is peer dependency and you need to require it in you app. Take a look at example app package.json. Thanks.
