### ISSUE TITLE
Date input validation

### ISSUE THREAD

**Issue by sinisterra** [networknt/react-schema-form#7]
I'm using tv4 as well to validate if the user input matches the schema. Everything works fine except for the date field. It breaks due to mismatched types (object instead of date), it can be seen in the demo showcasing Date. Are there any workarounds to this? Should I use instead another validation library?

Thanks!

**Comment by stevehu** [comment]
@sinisterra I am planning to switch to ajv in the future and I am wondering if you could help to implement it and test against date type.
https://github.com/ebdrup/json-schema-benchmark
Thanks.

**Comment by Anthropic** [comment]
@stevehu that is something we are wanting to look at with the json-schema-form core library, I want to expand our options for validators as it seems every month a different one takes the lead on the benchmarks, is-my-json-valid was easily the winner for about a year, so I suspect we will all be able to benefit from a unified core that accepts any validator with a minimal wrapper (to standardise error codes).

**Comment by stevehu** [comment]
@Anthropic I am monitoring json-schema-form core lib closely. Let's close this issue and track it over there.
