### ISSUE TITLE
Update peer dependencies

### ISSUE THREAD

**Issue by MrSaints** [networknt/react-schema-form#75]
I might be able to find time to do this, but:

```
warning "react-schema-form@0.3.11" has incorrect peer dependency "material-ui@^0.18.7".
warning "react-schema-form@0.3.11" has incorrect peer dependency "react@^15.3.2".
warning "react-schema-form@0.3.11" has incorrect peer dependency "react-dom@^15.3.2".
```

Ignoring the first, I've tested this component on React 16, and it appears to work fine.

**Comment by JFrankfurt** [comment]
I'd also very much appreciate it if someone could make this work and get the included example running on React ^16.3.0

**Comment by stevehu** [comment]
I have tried to upgrade the example to React 16.3.2 and material-ui v1beta during the weekend. There are some issues and I want your opinion. The material-ui v1beta is the only release that claims to support React 16 but it is still working in progress with some components missing like DatePicker etc. We cannot upgrade to React 16.3.2 and still keep material-ui with 0.x as there are some other issues. The safe move would be the latest version of React 15 and the latest version of material-ui 0.x. What do you think?

**Comment by stevehu** [comment]
@gtaschuk, @cheukwong,

Since this related to the DatePicker and Button Styling, it would be great if you can voice your opinions.

**Comment by stevehu** [comment]
https://material-ui-next.com/guides/migration-v0.x
