### ISSUE TITLE
Select not working ?

### ISSUE THREAD

**Issue by BastienAlvez** [networknt/react-schema-form#8]
Hi i try to use this schema form.
It works with radios, or input.
But i have some problem with select component. This one save name instead of value for key (titlemap) and also he always select the first option even if my model got data ...

**Comment by stevehu** [comment]
@BastienAlvez Could you please fork the repo and add you schema/firm to examples and l will debug into it. I personally don't use select but rc-select which supports multiple and tagging as well as dynamically loading items from rest apis.
Thanks.

**Comment by BastienAlvez** [comment]
I fork and add my json into examples/data/ (bicycleParking).

I will try to use rc-select thanks.

**Comment by stevehu** [comment]
@BastienAlvez 0.2.7 resolves this issue. Thanks for reporting it.

**Comment by BastienAlvez** [comment]
@stevehu Thanks !
The component selected the first option each time even if my model got a valid value. Is it normal ?
