### ISSUE TITLE
Dates as type string with format date-time

### ISSUE THREAD

**Issue by KevinPike** [networknt/react-schema-form#9]
Dates in my JSON schema are of type string and format date-time per http://spacetelescope.github.io/understanding-json-schema/reference/string.html However, I see that dates are currently rendered with type date. The validation library I'm using validates dates that are type string and format date-time so I would like to keep them that way instead of switching type to date.

From the examples, it looked like I could override the type using format `[{"key": "date", "type": "date"}]` but I'm getting the following error:

```
Uncaught TypeError: Cannot read property '0' of undefined
```

What do you recommend doing in this scenario? For now, I have a workaround where I modified date in utils.js to check for type string and format date-time.

**Comment by stevehu** [comment]
@KevinPike In JSON, date-time are formatted as string based on http://tools.ietf.org/html/rfc3339. Which validator are you using?

**Comment by KevinPike** [comment]
I am using https://github.com/xeipuuv/gojsonschema for json schema validation server side. A string with type date-time doesn't seem to render as a date time, just a text field.

**Comment by stevehu** [comment]
@KevinPike I am using Java json parser jackson and it parse the date/time without any issue. In a json file or stream, date/time is always in string format. I am not familiar with gojsonschema but I guess it might have some options to parse date/time just like Java parser.

**Comment by stevehu** [comment]
Not an issue on the schema form but backend json parser.
